hotel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^myorders/$', views.my_orders, name='my_orders'),
    
    url(r'^dashboard/admin/users/$', views.users_admin, name='users_admin'),
    url(r'^dashboard/admin/orders/$', views.orders_admin, name='orders_admin'),
    url(r'^dashboard/admin/foods/$', views.foods_admin, name='foods_admin'),
    url(r'^dashboard/admin/$', views.dashboard_admin, name='dashboard_admin'),
    url(r'^dashboard/admin/sales/$', views.sales_admin, name='sales_admin'),
    
    url(r'^dashboard/admin/users/add_user/$', views.add_user, name='add_user'),
    url(r'^dashboard/admin/foods/add_food/$', views.add_food, name='add_food'),
    url(r'^dashboard/admin/sales/add_sales/$', views.add_sales, name='add_sales'),
    url(r'^dashboard/admin/foods/editFood/(?P<foodID>\d+)/$', views.edit_food, name='edit_food'),
    url(r'^dashboard/admin/foods/foodDetails/(?P<foodID>\d+)/$', views.food_details, name='food_details'),
    url(r'^dashboard/admin/sales/editSale/(?P<saleID>\d+)/$', views.edit_sales, name='edit_sales'),
    
    url(r'^dashboard/admin/orders/confirm_order/(?P<orderID>\d+)/$', views.confirm_order, name='confirm_order'),
    url(r'^dashboard/admin/orders/confirm_delivery/(?P<orderID>\d+)/$', views.confirm_delivery, name='confirm_delivery'),
    
    url(r'^delete_item/(?P<ID>\d+)/$', views.delete_item, name='delete_item'),
    url(r'^add_deliveryBoy/(?P<orderID>\d+)/$', views.add_deliveryBoy, name='add_deliveryBoy'),
    url(r'^placeOrder/$', views.placeOrder, name='placeOrder'),
    url(r'^addTocart/(?P<foodID>\d+)/(?P<userID>\d+)/$', views.addTocart, name='addTocart'),

    url(r'^dashboard/delivery_boy/$', views.delivery_boy, name='delivery_boy'),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reflex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from hotel import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('hotel.urls', 'hotel'), namespace='hotel')),
    url(r'^', include('accounts.urls'))

]

templates/user/single.html
{% load static %}

{% include "../includes/landing_top.html" %}

<body>
	<div  class="bg-img">
		<!-- banner -->
		{% include "../includes/banner1.html" %}
		<!-- //banner -->
	</div>
	<!-- single -->
	<div class="blog">
				<!-- container -->
				<div class="container">
					<div class="col-md-8 blog-top-left-grid">
						<div class="left-blog left-single">
							<div class="blog-left">
								<div class="single-left-left">
									<p>Posted By <a href="#">Admin</a> &nbsp;&nbsp; on April 27, 2021 &nbsp;&nbsp; <a href="#">Comments (10)</a></p>
									<img src="/media/{{food.image}}" alt="">
								</div>
								<div class="blog-left-bottom">
									<p>{{food.content_description}}</p>
								</div>
								<a href="{% url 'hotel:addTocart' food.id request.user.id %}">
									<button class="btn btn-primary">Add to Cart</button>
								</a>
							</div>
							<div class="response">
								<h3>Responses</h3>
								<div class="media response-info">
									<div class="media-left response-text-left">
										<a href="#">
											<img class="media-object" src="{% static 'images/t1.jpg' %}" alt="">
										</a>
										<h5><a href="#">Admin</a></h5>
									</div>
									<div class="media-body response-text-right">
										<p>Thank You May God Bless You All</p>
										<ul>
											<li>April 27, 2021</li>
											<li><a href="single.html">Reply</a></li>
										</ul>
										<div class="media response-info">
											<div class="media-left response-text-left">
												<a href="#">
													<img class="media-object" src="{% static 'images/t2.jpg' %}" alt="">
												</a>
												<h5><a href="#">Admin</a></h5>
											</div>
											<div class="media-body response-text-right">
												<p>Thank You May God Bless You All</p>
												<ul>
													<li>May 27, 2021</li>
													<li><a href="single.html">Reply</a></li>
												</ul>		
											</div>
											<div class="clearfix"> </div>
										</div>
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="media response-info">
									<div class="media-left response-text-left">
										<a href="#">
											<img class="media-object" src="{% static 'images/t3.jpg' %}" alt="">
										</a>
										<h5><a href="#">Admin</a></h5>
									</div>
									<div class="media-body response-text-right">
										<p>Thank You May God Bless You All</p>
										<ul>
											<li>April 27, 2021</li>
											<li><a href="single.html">Reply</a></li>
										</ul>		
									</div>
									<div class="clearfix"> </div>
								</div>
							</div>
							
							<div class="opinion">
								<h2>Leave Your Comment</h2>
								<form action="#" method="post">
									<input type="text" name="Name" placeholder="Name" required="">
									<input type="text" name="Email" placeholder="Email" required="">
									<textarea name="Message" placeholder="Message" required=""></textarea>
									<input type="submit" value="SEND">
								</form>
							</div>
						</div>
					</div>
					<div class="col-md-4 blog-top-right-grid">
						<div class="categories">
							<h3>Categories</h3>
							<ul>
								<li><a href="#">Indian Best Food</a></li>
								<li><a href="#">South Indian Best Food</a></li>
								<li><a href="#">Gujarati Best Food</a></li>
								<li><a href="#">Punjabi Best Food</a></li>
								<li><a href="#"> Best Food</a></li>
								<li><a href="#">Fast Food</a></li>
							</ul>
						</div>
						<div class="categories">
							<h3>Archive</h3>
							<ul class="marked-list offs1">
								<li><a href="#">January 2021 (7)</a></li>
                                <li><a href="#">February 2021 (11)</a></li>
                                <li><a href="#">March 2021 (12)</a></li>
                                <li><a href="#">April 2021 (14)</a> </li>
                                <li><a href="#">May 2021 (10)</a></li>    
                                <li><a href="#">June 2021 (12)</a></li>
                                <li><a href="#">July 2021 (8)</a></li>
                                <li><a href="#">August 2021 (7)</a> </li>
                                <li><a href="#">September 2021 (8)</a></li>
                                <li><a href="#">October 2021 (6)</a></li>
                                <li><a href="#">November 2021 (6)</a></li>  
                                <li><a href="#">December 2021 (6)</a></li>                          
							</ul>
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<!-- //container -->
	</div>
	<!-- //single -->
	{% include "../includes/footer.html" %}