hotel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^myorders/$', views.my_orders, name='my_orders'),
    
    url(r'^dashboard/admin/users/$', views.users_admin, name='users_admin'),
    url(r'^dashboard/admin/orders/$', views.orders_admin, name='orders_admin'),
    url(r'^dashboard/admin/foods/$', views.foods_admin, name='foods_admin'),
    url(r'^dashboard/admin/$', views.dashboard_admin, name='dashboard_admin'),
    url(r'^dashboard/admin/sales/$', views.sales_admin, name='sales_admin'),
    
    url(r'^dashboard/admin/users/add_user/$', views.add_user, name='add_user'),
    url(r'^dashboard/admin/foods/add_food/$', views.add_food, name='add_food'),
    url(r'^dashboard/admin/sales/add_sales/$', views.add_sales, name='add_sales'),
    url(r'^dashboard/admin/foods/editFood/(?P<foodID>\d+)/$', views.edit_food, name='edit_food'),
    url(r'^dashboard/admin/foods/foodDetails/(?P<foodID>\d+)/$', views.food_details, name='food_details'),
    url(r'^dashboard/admin/sales/editSale/(?P<saleID>\d+)/$', views.edit_sales, name='edit_sales'),
    
    url(r'^dashboard/admin/orders/confirm_order/(?P<orderID>\d+)/$', views.confirm_order, name='confirm_order'),
    url(r'^dashboard/admin/orders/confirm_delivery/(?P<orderID>\d+)/$', views.confirm_delivery, name='confirm_delivery'),
    
    url(r'^delete_item/(?P<ID>\d+)/$', views.delete_item, name='delete_item'),
    url(r'^add_deliveryBoy/(?P<orderID>\d+)/$', views.add_deliveryBoy, name='add_deliveryBoy'),
    url(r'^placeOrder/$', views.placeOrder, name='placeOrder'),
    url(r'^addTocart/(?P<foodID>\d+)/(?P<userID>\d+)/$', views.addTocart, name='addTocart'),

    url(r'^dashboard/delivery_boy/$', views.delivery_boy, name='delivery_boy'),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reflex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from hotel import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('hotel.urls', 'hotel'), namespace='hotel')),
    url(r'^', include('accounts.urls'))

]

templates/admin_temp/foods.html
{% load static %} 

{% include "includes/base.html" %} 
{% include "includes/navbarheader.html" %} 
{% include "includes/navtop.html"%}
{% include "includes/sidemenu.html" %}

</nav>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Foods Information</h1>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addFood">
                Add Food
            </button>
            <br><br>
            <div id="addFood" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add Food</h4>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{% url 'hotel:add_food' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name:</label>
                                    <input type="text" class="form-control" id="name" name="name">
                                </div>
                                <div class="form-group">
                                    <label for="course">Course:</label>
                                    <select class="dropdown" id="course" name="course">
                                        <option selected="selected">------</option>
                                        <option value="Indian">Indian Best Food</option>
                                        <option value="Gujarati">Gujarati Best Food</option>
                                        <option value="South">South-Indian Best Food </option>
                                        <option value="Punjabi">Punjabi Best Food</option>
                                        <option value="Fast">Fast Food</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="status">Status:</label>
                                    <select class="dropdown" id="status" name="status">
                                        <option selected="selected">------</option>
                                        <option value="Disabled">Disabled</option>
                                        <option value="Enabled">Enabled</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="content">Content Description:</label>
                                    <input type="text" class="form-control" id="content" name="content">
                                </div>
                                <div class="form-group">
                                    <label for="base_price">Base Price:</label>
                                    <input type="number" class="form-control" id="base_price" name="base_price" value=0>
                                </div>
                                <div class="form-group">
                                    <label for="discount">Discount(%):</label>
                                    <input type="number" class="form-control" id="discount" name="discount" value=0>
                                </div>
                                <div class="form-group">
                                    <label for="image">Image:</label>
                                    <input type="file" class="form-control" id="image" name="image">
                                </div>
                                <button type="submit" class="btn btn-default">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List of all Dishes of the Restaurant
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Course</th>
                                <th>Description</th>
                                <th>Base Price</th>
                                <th>Discount(%)</th>
                                <th>Sale Price</th>
                                <th>Status</th>
                                <th>Expense/Sales</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for food in foods %}
                            <tr>
                                <td><img src="/media/{{food.image}}" width="45" height="45"></td>
                                <td>{{food.name}}</td>
                                <td>{{food.course}}</td>
                                <td>{{food.content_description|truncatechars:150}}</td>
                                <td>{{food.base_price}}</td>
                                <td>{{food.discount}} %</td>
                                <td>{{food.sale_price}}</td>
                                <td>{% if food.status == 'Enabled' %}
                                    <span class="label label-success">Enabled</span>
                                    {% else %}
                                    <span class="label label-danger">Disabled</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true">{{food.id}}</span>
                                    </button>
                                   
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div id="myModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Edit Food Details</h4>
                                </div>
                                <div class="modal-body">
                                    <form method="POST" action="/mysite/foods/editFood/{{foods.id}}/">
                                        {% csrf_token %}
                                
                                        
                                        <div class="form-group">
                                            <label for="base_price">Base Price:{{foods.id}}</label>
                                            <input type="number" class="form-control" id="base_price" name="base_price">
                                        </div>
                                        <div class="form-group">
                                            <label for="discount">Discount(%):</label>
                                            <input type="number" class="form-control" id="discount" name="discount">
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="disabled" {% ifequal food.status 'Disabled' %}checked{% endifequal %}>Not Available
                                            </label>
                                        </div>
                                        
                                        <button type="submit" class="btn btn-default">Submit</button>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>

<!-- DataTables JavaScript -->
<script src="{% static '/vendor/datatables/js/jquery.dataTables.min.js'%}"></script>
<script src="{% static '/vendor/datatables-plugins/dataTables.bootstrap.min.js'%}"></script>
<script src="{% static '/vendor/datatables-responsive/dataTables.responsive.js'%}"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'vendor/metisMenu/metisMenu.min.js'%}"></script>
<script src="{% static 'dist/js/sb-admin-2.js'%}"></script>

</body>

</html>

templates/admin_temp/index.html
{% load static %}
{% include "includes/base.html" %}
{% include "includes/navbarheader.html" %}
{% include "includes/navtop.html" %}
{% include "includes/sidemenu.html" %}
{% include "includes/scripts.html" %}

</nav>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Dashboard</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{comments}}</div>
                            <div>Total Comments!</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{customers}}</div>
                            <div>Total Customers!</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'hotel:users_admin' %}">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{orders}}</div>
                            <div>Total Orders!</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'hotel:orders_admin' %}">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-support fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{sales}}</div>
                            <div>Total Sales!</div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'hotel:sales_admin' %}">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right">
                            <i class="fa fa-arrow-circle-right"></i>
                        </span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Top Customers
                        </div>
                        <!-- /.panel-heading -->
                        <table class="table">
                          <thead>
                            <tr>
                              <th scope="col">Customer Name</th>
                              <th scope="col">#Orders</th>
                              <th scope="col">Total Sale</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for customer in top_customers %}
                            <tr>
                              <td>{{customer.customer.first_name}} {{customer.customer.last_name}}</td>
                              <td>{{customer.orders}}</td>
                              <td>{{customer.total_sale}}</td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                        <!-- /.panel-body -->
                    </div>

                    <!-- /.panel .chat-panel -->
                </div>
                <!-- /.col-lg-4 -->
                <div class="col-lg-8">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Latest Orders
                        </div>
                        <!-- /.panel-heading -->
                        <table class="table">
                          <thead>
                            <tr>
                              <th scope="col">ID</th>
                              <th scope="col">Location</th>
                              <th scope="col">Customer Name</th>
                              <th scope="col">Type</th>
                              <th scope="col">Order Timestamp</th>
                              <th scope="col">Total Amount</th>
                              <th scope="col">Satus</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for order in latest_orders %}
                            <tr>
                              <td>{{order.id}}</td>
                              <td>{{order.location}}</td>
                              <td>{{order.customer.customer.first_name}} {{order.customer.customer.last_name}}</td>
                              <td>Delivery</td>
                              <td>{{order.order_timestamp}}</td>
                              <td>{{order.total_amount}}</td>
                              <td>
                                  {% if order.delivery_status == "Completed" %}
                                    <span class="label label-success">Delivered</span>
                                  {% elif order.delivery_status == "Processing" %}
                                    <span class="label label-warning">Processing</span>
                                  {% else %}
                                    <span class="label label-danger">Pending</span>
                                  {% endif %}
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                        <!-- /.panel-body -->
                    </div>
                </div>
            </div>

            <div id="chart_div" style="width: 100%; height: 500px;"></div>
            <!-- /.row -->
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

templates/admin_temp/sales.html
{% load static %} 
{% include "includes/base.html" %} 
{% include "includes/navbarheader.html" %} 
{% include "includes/navtop.html"%}
{% include "includes/sidemenu.html" %}

</nav>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Hotel Sales Information</h1>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addFood">
                Add Sales Data
            </button>
            <br>
            <br>
            <div id="addFood" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add Sales data</h4>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{% url 'hotel:add_sales' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="date">Date:</label>
                                    <input type="date" class="form-control" id="date" name="date">
                                </div>
                                <div class="form-group">
                                    <label for="sales">Sales:</label>
                                    <input type="number" class="form-control" id="sales" name="sales">
                                </div>
                                <div class="form-group">
                                    <label for="expenses">Expenses:</label>
                                    <input type="number" class="form-control" id="expenses" name="expenses">
                                </div>
                                <button type="submit" class="btn btn-default">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    List of all the Sales of the Restaurant
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Date</th>
                                <th>Sales</th>
                                <th>Expenses</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sale in sales %}
                            <tr>
                                <td>{{sale.id}}</td>
                                <td>{{sale.date}}</td>
                                <td>{{sale.sales}}</td>
                                <td>{{sale.expenses}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal{{sale.id}}">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </button>
                                    <div id="modal{{sale.id}}" class="modal fade" role="dialog">
                                        <div class="modal-dialog">

                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Edit Sales Details</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <form method="POST" action="{% url 'hotel:edit_sales' sale.id%}">
                                                        {% csrf_token %}
                                                        <div class="form-group">
                                                            <label for="sales">Sales:</label>
                                                            <input type="number" class="form-control" id="sales" name="sales" value="{{sale.sales}}">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="expenses">Expenses:</label>
                                                            <input type="number" class="form-control" id="expenses" name="expenses" value="{{sale.expenses}}">
                                                        </div>
                                                        <button type="submit" class="btn btn-default">Submit</button>
                                                    </form>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>

<!-- DataTables JavaScript -->
<script src="{% static '/vendor/datatables/js/jquery.dataTables.min.js'%}"></script>
<script src="{% static '/vendor/datatables-plugins/dataTables.bootstrap.min.js'%}"></script>
<script src="{% static '/vendor/datatables-responsive/dataTables.responsive.js'%}"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'vendor/metisMenu/metisMenu.min.js'%}"></script>
<script src="{% static 'dist/js/sb-admin-2.js'%}"></script>

</body>

</html>